name: Prepar build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile Metis
      run: |
        cd metisLib
        tar -xvzf metis-5.1.0.tar.gz
        cd metis-5.1.0
        make config
        make
        mkdir -p ./../../lib/
        cp -v build/Linux-x86_64/libmetis/libmetis.a ../../lib/
        cd ../../

    - name: Compile prepar
      run: |
        cp -v contrib/Makefile_base Makefile
        make

    - name: Run prepar
      run: |
        tar -xvzf contrib/examples/solo.tar.gz -C bin/
        cp bin/prepar bin/solo
        cd bin/solo
        ./prepar pre.dat
